<?php

require_once('../TCPDF-main/tcpdf.php');
require ('db_connect.php');

$get=$conn->query("SELECT * FROM `scholar` left join `program` on program.program_id = scholar.program_id where scholar.status = 'A' OR scholar.status = 'I'") or die(mysqli_error());
		
		// if($get->num_rows > 0 ){
		// 	$data = $get->fetch_array();
		// }	
 /**
 * undocumented class
 */

class PDF extends TCPDF
{
    public function Header(){
        $imageFile = K_PATH_IMAGES.'tesdalogo.jpg';
        $this->Image($imageFile, 90, 10, 40, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        $this->SetY(25);
        $this->setFont('helvetica', 'B', 12);
        $this->Cell(189, 5, 'TESDA Scholarship Monitoring System', 0, 1, 'C');
        $this->SetFont('helvetica', '', 8);
        $this->Cell(189, 3, '0917-479-4370 (text only)', 0, 1, 'C');
        $this->Cell(189, 3, '8887-7777', 0, 1, 'C');
        $this->Cell(189, 3, 'contactcenter@tesda.gov.ph', 0, 1, 'C');
        $this->SetFont('helvetica', 'B', 14);
        $this->Ln(2);
    }
    public function Footer(){
        date_default_timezone_set("Asia/Manila");
        $today = date("F j, Y/g:i A", time());
        $day = date("j");
        $month = date("F");
        $year = date("Y");

        // $this->SetY(-120);
        // $this->Ln(5);
        // $this->SetFont('times', 'B', 11);
        // $this->Cell(189, 5, '**TESDA Scholar Monitoring System**', 0, 1);
        // $this->Ln();
        // $this->Cell(189, 5, '**Generated by: ADMIN**', 0, 1);
        // $this->Ln();
        // $this->Cell(189, 5, '**Contact Information:**', 0, 1);
        // $this->SetFont('times', '', 11);
        // $this->Cell(189, 5, 'TESDA Scholar Monitoring System', 0, 1);
        // $this->Cell(189, 5, '0917-479-4370 (text only)', 0, 1);
        // $this->Cell(189, 5, '8887-7777', 0, 1);
        // $this->Cell(189, 5, 'contactcenter@tesda.gov.ph', 0, 1);
        // $this->SetFont('times', 'B', 11);
        // $this->Ln();
        // $this->Cell(189, 5, '**Disclaimer:**', 0, 1);
        // $this->Cell(189, 5, 'This report is generated for monitoring purposes only.', 0, 1);
        // $this->SetFont('times', '', 11);

        $this->SetFont('helvetica','I',8);

        $this->SetY(-20);
        $this->Cell(25,5,'Date/Time: '.$today,0,0,'L');
        $this->Cell(164,5,'Page '.$this->getAliasNumPage().' of '.$this->getAliasNumPage(),0,false,'R',0,'',0,false,'T','M');
    }
}


// create new PDF document
$pdf = new PDF('P', 'mm', 'A4', true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('TESDA Scholarship Monitoring System');
$pdf->SetTitle('Exported Data');
$pdf->SetSubject('TCertificate of Employment');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 001', PDF_HEADER_STRING, array(0,64,255), array(0,64,128));
$pdf->setFooterData(array(0,64,0), array(0,64,128));

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// set default font subsetting mode
$pdf->setFontSubsetting(true);

// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
$pdf->SetFont('dejavusans', '', 8, '', true);

// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();

$html = <<<EOD
    <table cellspacing="0" cellpadding="1" border="1" style="border-color:gray;text-align:center;">
      <tr>
        <td width="20%">Full Name</td>
        <td width="20%">Email</td>
        <td width="20%">Phone</td>
        <td width="40%">Program Name</td>
      </tr>
EOD;

if ($get->num_rows > 0) {
    while ($row = $get->fetch_assoc()) {
        $html .= <<<EOD
        <tr>
            <td>{$row['fname']} {$row['lname']}</td>
            <td>{$row['email']}</td>
            <td>{$row['phone']}</td>
            <td>{$row['program_name']}</td>
        </tr>
EOD;
    }
}

$html .= "</table>";


// Print text using writeHTMLCell()
$pdf->writeHTMLCell(0, 0, '', 50, $html, 0, 1, 0, true, '', true);

// Close and output PDF document
// This method has several options, check the source code documentation for more information.

$current_month_year = date('FY'); // returns the current month and year in the format "MonthYYYY"
$file_name = "TESDA_Exported_Process_{$current_month_year}.pdf";

$pdf->Output($file_name, 'I');
?>